package de.emp2020.alertEditor;

import java.util.List;

public class AlertJson {
	
	private int alertId;
	private String title;
	private String promQuery;
	private String description;
	private String owner;
	
	private List<String> assignedUsers;
	
	
	// Autogenerated Getters and Setters
	
	public int getAlertId() {
		return alertId;
	}

	public void setAlertId(int alertId) {
		this.alertId = alertId;
	}

	public String getTitle() {
		return title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getPromQuery() {
		return promQuery;
	}

	public void setPromQuery(String promQuery) {
		this.promQuery = promQuery;
	}

	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getOwner() {
		return owner;
	}

	public void setOwner(String owner) {
		this.owner = owner;
	}

	public List<String> getAssignedUsers() {
		return assignedUsers;
	}

	public void setAssignedUsers(List<String> assignedUsers) {
		this.assignedUsers = assignedUsers;
	}
	
	
	
}
